title: Delong LI # your name (or website title) here
logo: "/images/photo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  ## 5+ years studying and working experience as Data Scientist. Proficient in Python, SQL, Git, Docker, Airflow, PowerBI. 
  <br><br>
  ## Fields of interest: NLP, Recommender System, Computer Vision. 
  <br><br>
  <a href="https://www.linkedin.com/in/delongli/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

